---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    matchLabels:
      app: giropops-senhas
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - giropops-senhas
              topologyKey: kubernetes.io/hostname
      containers:
        - image: ablackout3/giropops-senhas:latest
          name: giropops-senhas
          env:
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            requests:
              cpu: "120m"
              memory: "64M"
            limits:
              cpu: "140m"
              memory: "128M"
          ports:
            - containerPort: 5000
              name: flask
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          imagePullPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: giropops-senhas
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: giropops-senhas
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  type: ClusterIP
  ports:
    - name: flask
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: giropops-senhas
  endpoints:
    - interval: 10s
      path: /metrics
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
  labels:
    name: giropops-senhas
spec:
  ingressClassName: nginx
  rules:
    - host: giropops-senhas.antonioazambuja.dev
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: giropops-senhas
                port:
                  number: 5000
