checks:
  addAllBuiltIn: true
  exclude:
    - "default-service-account"
    - "dnsconfig-options"
    - "no-node-affinity"
    - "non-isolated-pod"
    - "required-label-owner"
    - "use-namespace"
    - "latest-tag"
    - "required-annotation-email"
    - "minimum-three-replicas"