---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  template:
    spec:
      containers:
        - name: giropops-senhas
          livenessProbe:
            initialDelaySeconds: 10
          readinessProbe:
            initialDelaySeconds: 10