---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-antonioazambuja
  labels:
    app: redis-antonioazambuja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-antonioazambuja
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-antonioazambuja
    spec:
      containers:
        - image: cgr.dev/chainguard/redis:latest
          name: redis-antonioazambuja
          resources:
            requests:
              cpu: "0.5m"
              memory: "256M"
            limits:
              cpu: "0.8m"
              memory: "512M"
          ports:
            - containerPort: 6379
              name: redis
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: redis-antonioazambuja
  labels:
    app: redis-antonioazambuja
spec:
  selector:
    app: redis-antonioazambuja
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379