---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pick-linuxtips
  region: us-east-1
  version: '1.28'
  tags:
    cluster-name: pick-linuxtips
    owner: antonioazambuja

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

addons:
  - name: aws-ebs-csi-driver
    version: 1.26.1
  - name: aws-efs-csi-driver
    version: 1.7.3

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-ebs-csi-driver
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: default
      labels: {aws-usage: "cluster-ops"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
  - metadata:
      name: aws-efs-csi-driver
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      namespace: default
      labels: {aws-usage: "cluster-ops"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy"

nodeGroups:
  - name: t3-small
    minSize: 6
    maxSize: 6
    instanceType: t3.small
    volumeType: gp2
    desiredCapacity: 6
    volumeSize: 80
