---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas
  namespace: develop
  labels:
    app: giropops-senhas
spec:
  template:
    spec:
      containers:
        - name: giropops-senhas
          livenessProbe:
            initialDelaySeconds: 5
          readinessProbe:
            initialDelaySeconds: 5