name: CI/CD

on:
  push:
    branches:
      - "main"
      - "develop"

env:
  VERSION_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:0.${{ github.run_number }}
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:latest
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Build before Trivy Scan
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     tags: ${{ env.LATEST_TAG }}

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: ${{ env.LATEST_TAG }}

    # - name: Create k8s Kind Cluster
    #   uses: helm/kind-action@v1.8.0
    #   with:
    #     cluster_name: kind-pick

    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ env.VERSION_TAG }},${{ env.LATEST_TAG }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy Redis
      uses: actions-hub/kubectl@v1.29.0
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods

    # - name: Deploy giropops-senhas
    #   uses: actions-hub/kubectl@v1.29.0
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: apply -f k8s/