name: CI

on: # somente em alterações de pastas especificas
  push:
    paths:
      - 'Dockerfile'
      - '**.js'
      - '**.py'
      - '**.txt'
      - 'templates/**'
      - 'static/**'

env:
  VERSION_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:0.${{ github.run_number }}
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:latest

permissions:
  contents: read

jobs:
  sast:
    name: SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build before Trivy Scan
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ env.LATEST_TAG }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.LATEST_TAG }}

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production
    needs: [sast]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.2.2'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.VERSION_TAG }},${{ env.LATEST_TAG }}

  cosign:
    name: Cosign
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production
    needs: [build]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.2.2'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Sign the container image ${{ env.LATEST_TAG }}
      run: cosign sign --yes ${{ env.LATEST_TAG }}

    - name: Sign the container image ${{ env.VERSION_TAG }}
      run: cosign sign --yes ${{ env.VERSION_TAG }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.10.0
      with:
        config: kind/cluster.yaml
    - run: make test-app-github-actions
