name: CI/CD

on: # somente em alterações de pastas especificas
  push:
    branches:
      - "main"
      - "develop"

env:
  VERSION_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:0.${{ github.run_number }}
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/giropops-senhas:latest
  # AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build before Trivy Scan
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ env.LATEST_TAG }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.LATEST_TAG }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.VERSION_TAG }},${{ env.LATEST_TAG }}

    # - name: Create k8s Kind Cluster
    #   uses: helm/kind-action@v1.8.0
    #   with:
    #     config: kind/cluster.yaml
    # - run: |
    #     make install-cluster-deps
    #     make redis-deploy
    #     make giropops-senhas-deploy-without-ingress
    #     make run-load-test-k6-operator
