name: Integration Test

on: # somente em alterações de pastas especificas
  push:
    branches:
      - 'develop'
    paths:
      - '**.yaml'
      - 'Makefile'

permissions:
  contents: read

jobs:
  kind:
    name: Kind Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production