name: CI - Testing my environment

on: # somente em alterações de pastas especificas
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - '**.yaml'
      - 'Makefile'

permissions:
  contents: read

jobs:
  kind:
    name: Kind Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.10.0
      with:
        config: kind/cluster.yaml
    - run: |
        make test-app-github-actions
