name: YAML & K8s Lint

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - '**.yaml'

permissions:
  contents: read

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Yamllint K8s manifests'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: 'manifests/base'
        yamllint_config_filepath: '.yamllint.yaml'

    - name: 'Yamllint Kustomize Overlay EKS'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: 'manifests/overlays/eks'
        yamllint_config_filepath: '.yamllint.yaml'

    - name: 'Yamllint Kustomize Overlay Local'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: 'manifests/overlays/local'
        yamllint_config_filepath: '.yamllint.yaml'

    - name: 'Yamllint EKS Cluster'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: 'eks/'
        yamllint_config_filepath: '.yamllint.yaml'

    - name: 'Yamllint Kind Cluster'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: 'kind/'
        yamllint_config_filepath: '.yamllint.yaml'

    - name: 'Yamllint Load Test - K6 Operator manifests'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: 'load-test/'
        yamllint_config_filepath: '.yamllint.yaml'

  k8s-lint:
    name: Kubernetes Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: kube-linter K8s manifests
      uses: stackrox/kube-linter-action@v1
      with:
        directory: manifests/base
        config: .kube-linter.yaml

    - name: kube-linter K6 manifests
      uses: stackrox/kube-linter-action@v1
      with:
        directory: load-test
        config: .kube-linter.yaml
