apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.redis.labels.app }}
  name: {{ .Values.redis.name }}
spec:
  clusterIP: None
  ports:
{{- range .Values.redis.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
{{- end }}
  selector:
    app: redis